# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
    "*.css",
    "*.html",
    "*.js",
    "*.json",
    "*.jsx",
    "*.md",
    "*.mdx",
    "*.scss",
    "*.ts",
    "*.yaml",
]
excludes = ["CHANGELOG.md"]

[formatter.rust]
command = "rustfmt"
options = [
    "--edition",
    "2021",
    "--config",
    "format_macro_matchers=true,format_macro_bodies=true"
]
includes = ["*.rs"]

[formatter.shell]
command = "shfmt"
options = [
    "-i",
    "2",  # indent 2
    "-s",  # simplify the code
    "-w",  # write back to the file
]
includes = ["*.sh"]
